# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 06:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liscence_no', models.CharField(max_length=30, verbose_name='liscence_no')),
                ('scanned', models.ImageField(blank=True, upload_to='', verbose_name="picture of driver's liscence")),
                ('car_picture', models.ImageField(upload_to='pictures/')),
                ('number_plates', models.CharField(max_length=30)),
                ('capacity', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=30)),
                ('city', models.CharField(max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.CharField(max_length=30)),
                ('scanned', models.ImageField(blank=True, upload_to='', verbose_name='picture of passenger')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=30)),
                ('location', models.CharField(max_length=60)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=60)),
                ('cost', models.IntegerField()),
                ('start_time', models.TimeField(max_length=60)),
                ('no_pass', models.IntegerField(verbose_name='no of passengers')),
                ('ended', models.BooleanField(default=False, verbose_name='sharing ended')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
