# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='passenger',
            field=models.CharField(max_length=30),
        ),
    ]
